import {
  Airplane01Icon,
  Alert01Icon,
  AppleIcon,
  ArrowDataTransferHorizontalIcon,
  ArrowDown01Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  ArrowRight02Icon,
  ArrowUp01Icon,
  AtIcon,
  BookOpen01Icon,
  Bookmark01Icon,
  Calendar03Icon,
  Camera01Icon,
  Cancel02Icon,
  Copy01Icon,
  CreditCardIcon,
  Delete02Icon,
  Download04Icon,
  ExternalLinkIcon,
  EyeIcon,
  EyeOffIcon,
  FoldHorizontalIcon,
  GlobeIcon,
  HelpCircleIcon,
  LanguagesIcon,
  Layout01Icon,
  Legal01Icon,
  LegalDocument01Icon,
  Location01Icon,
  LockIcon,
  Logout01Icon,
  Luggage01Icon,
  Mail01Icon,
  MapsIcon,
  Menu01Icon,
  MinusSignIcon,
  Moon02Icon,
  MoreHorizontalIcon,
  Orbit01Icon,
  PaintBoardIcon,
  PanelLeftIcon,
  PencilEdit01Icon,
  PlayStoreIcon,
  PlusSignIcon,
  Share01Icon,
  Shield01Icon,
  SparklesIcon,
  SquareStackIcon,
  Sun02Icon,
  Tick04Icon,
  UnfoldMoreIcon,
  User02Icon,
} from "@hugeicons/core-free-icons";
import type { IconName, IconSvgObject } from "./types";

export const iconMap = {
  alert: Alert01Icon,
  apple: AppleIcon,
  "arrow-right": ArrowRight02Icon,
  at: AtIcon,
  "book-open": BookOpen01Icon,
  bookmark: Bookmark01Icon,
  calendar: Calendar03Icon,
  camera: Camera01Icon,
  check: Tick04Icon,
  delete: Delete02Icon,
  download: Download04Icon,
  chevronDown: ArrowDown01Icon,
  "chevron-left": ArrowLeft01Icon,
  "chevron-right": ArrowRight01Icon,
  "chevron-up": ArrowUp01Icon,
  "chevron-up-down": UnfoldMoreIcon,
  close: Cancel02Icon,
  copy: Copy01Icon,
  "credit-card": CreditCardIcon,
  document: LegalDocument01Icon,
  edit: PencilEdit01Icon,
  "external-link": ExternalLinkIcon,
  eye: EyeIcon,
  "eye-off": EyeOffIcon,
  fold: FoldHorizontalIcon,
  globe: GlobeIcon,
  help: HelpCircleIcon,
  languages: LanguagesIcon,
  layout: Layout01Icon,
  legal: Legal01Icon,
  loading: Orbit01Icon,
  location: Location01Icon,
  lock: LockIcon,
  logout: Logout01Icon,
  luggage: Luggage01Icon,
  mail: Mail01Icon,
  map: MapsIcon,
  menu: Menu01Icon,
  minus: MinusSignIcon,
  moon: Moon02Icon,
  more: MoreHorizontalIcon,
  palette: PaintBoardIcon,
  "panel-left": PanelLeftIcon,
  plane: Airplane01Icon,
  "play-store": PlayStoreIcon,
  plus: PlusSignIcon,
  "photo-stack": SquareStackIcon,
  share: Share01Icon,
  shield: Shield01Icon,
  sparkles: SparklesIcon,
  sun: Sun02Icon,
  swap: ArrowDataTransferHorizontalIcon,
  user: User02Icon,
} as const satisfies Record<string, IconSvgObject>;

// This gives a typed array of keys
export const iconNames = Object.keys(iconMap) as IconName[];
